"""P1 MLIP relaxation stage ([P1] athermal relaxation & stability).

CONTENTS:
- sharding.py: stateless batch protocol (v2 batch_id, SHARD=i/OF=M split,
  atomic result files, legacy guard, resume-by-structure-hash).
  CPU-tested with stub relaxations; MLIP-agnostic by design.
- relax.py: real mace_mp("medium-mpa-0") relaxation + manifest writer.
- analysis.py: post-relax structural metrics + parent-collapse annotation.
- gitpush.py: worker-side commit/push safety (done files only, never main).

See DESIGN.md (finalized 2026-09) before touching anything here.
"""

from rudeus.mlip.analysis import (
    annotate_post_relax_novelty,
    compare_structures,
)
from rudeus.mlip.gitpush import (
    GitSafetyError,
    commit_done_files,
    push_branch,
    select_commit_files,
)
from rudeus.mlip.p2 import (
    P2_PROTOCOL_DEFAULTS,
    DiagnosticStall,
    build_p2_result,
    evaluate_p2,
    load_authorization_manifest,
    mic_step_jump,
    min_image_distances,
    p2_job_seed,
    partition_host_mobile,
    protocol_config_hash,
    run_nvt,
    run_p2_batches,
    unwrap_trajectory,
)
from rudeus.mlip.calibration import (
    load_calibration_records,
    make_calibration_job,
    make_md_runner,
    run_calibration,
    summarize_calibration,
)
from rudeus.mlip.validation import (
    GPU_RUN,
    GPU_UNRESOLVED,
    VALIDATION_CASES,
    VALIDATION_VERSION,
    build_validation_report,
    check_cpu8000_eligible,
    collect_backend_versions,
    describe_comparison,
    detect_environment,
    resolve_case,
    run_validation,
    CaseUnavailable,
)

from rudeus.mlip.sharding import (
    BATCH_ID_SCHEME_V2,
    ERROR_VERDICTS,
    SKIPPED_VERDICTS,
    make_batch_id,
    make_batch_id_v1,
    structure_dict_sha256,
    assign_shard,
    shard_batches,
    write_json_atomic,
    make_batch_file,
    run_batches,
)
from rudeus.mlip.gpu_diagnostic import (
    DIAGNOSTIC_VERSION,
    benchmark_forces,
    check_cuequivariance,
    compare_cpu_cuda,
    cuda_memory_snapshot,
    mini_md,
    probe_calculator,
    resolve_device,
    resolve_diagnostic_candidate,
    run_diagnostic,
)
from rudeus.mlip.stall_diagnostic import (
    STALL_OUT_DIR,
    HeartbeatRecorder,
    TimingCalculator,
    check_stall,
    classify_termination,
    ensure_diag_out_dir,
    run_stall_diagnostic,
    summarize_frames,
)
from rudeus.mlip.relax import (
    default_model_path,
    sha256_file,
    ensure_checkpoint,
    load_calculator,
    energies_match,
    relax_structure,
    ENERGY_MATCH_TOL_MEV_PER_ATOM_PROVISIONAL,
)

__all__ = [
    "BATCH_ID_SCHEME_V2",
    "ERROR_VERDICTS",
    "SKIPPED_VERDICTS",
    "make_batch_id",
    "make_batch_id_v1",
    "structure_dict_sha256",
    "assign_shard",
    "shard_batches",
    "write_json_atomic",
    "make_batch_file",
    "run_batches",
    "DIAGNOSTIC_VERSION",
    "benchmark_forces",
    "check_cuequivariance",
    "compare_cpu_cuda",
    "cuda_memory_snapshot",
    "mini_md",
    "probe_calculator",
    "resolve_device",
    "resolve_diagnostic_candidate",
    "run_diagnostic",
    "annotate_post_relax_novelty",
    "compare_structures",
    "GitSafetyError",
    "commit_done_files",
    "push_branch",
    "select_commit_files",
    "P2_PROTOCOL_DEFAULTS",
    "DiagnosticStall",
    "build_p2_result",
    "evaluate_p2",
    "load_authorization_manifest",
    "mic_step_jump",
    "min_image_distances",
    "p2_job_seed",
    "partition_host_mobile",
    "protocol_config_hash",
    "run_nvt",
    "run_p2_batches",
    "unwrap_trajectory",
    "load_calibration_records",
    "make_calibration_job",
    "make_md_runner",
    "run_calibration",
    "summarize_calibration",
    "GPU_RUN",
    "GPU_UNRESOLVED",
    "VALIDATION_CASES",
    "VALIDATION_VERSION",
    "build_validation_report",
    "check_cpu8000_eligible",
    "collect_backend_versions",
    "describe_comparison",
    "detect_environment",
    "resolve_case",
    "run_validation",
    "CaseUnavailable",
    "STALL_OUT_DIR",
    "HeartbeatRecorder",
    "TimingCalculator",
    "check_stall",
    "classify_termination",
    "ensure_diag_out_dir",
    "run_stall_diagnostic",
    "summarize_frames",
    "default_model_path",
    "sha256_file",
    "ensure_checkpoint",
    "load_calculator",
    "energies_match",
    "relax_structure",
    "ENERGY_MATCH_TOL_MEV_PER_ATOM_PROVISIONAL",
]